### ISSUE TITLE
Error on Create Notification 

### ISSUE THREAD

**Issue by SueHeir** [OneSignal/node-onesignal#16]
Hello! I am getting the following error when trying to create a notification.

Here is the code I am running
```node
const OneSignal = require("@onesignal/node-onesignal");

  let configuration = OneSignal.createConfiguration({
    authMethods: {
      user_key: {
        tokenProvider: user_key_provider,
      },
      app_key: {
        tokenProvider: app_key_provider,
      },
    },
  });

  const OneSignalclient = await new OneSignal.DefaultApi(configuration);

  const OneSignalApp = await OneSignalclient.getApp(MY_APP_ID);
```

```node
  const notification = new OneSignal.Notification();
  notification.app_id = OneSignalApp.id;
  notification.contents = {
    en: "contents is here",
  };
  notification.headings = {
    en: "heading is here",
  };
  notification.include_external_user_ids = ["2"];

  await OneSignalclient.createNotification(notification, {
    Authorization: MY_API_KEY});
```

Here is the error:

`TypeError: Cannot read properties of undefined (reading 'makeRequestContext')
    at DefaultApiRequestFactory.<anonymous> (/home/elizabeth/Programming/Websites/debacle/server/node_modules/@onesignal/node-onesignal/dist/apis/DefaultApi.js:137:61)
    at step (/home/elizabeth/Programming/Websites/debacle/server/node_modules/@onesignal/node-onesignal/dist/apis/DefaultApi.js:46:23)
    at Object.next (/home/elizabeth/Programming/Websites/debacle/server/node_modules/@onesignal/node-onesignal/dist/apis/DefaultApi.js:27:53)
    at /home/elizabeth/Programming/Websites/debacle/server/node_modules/@onesignal/node-onesignal/dist/apis/DefaultApi.js:21:71
    at new Promise (<anonymous>)
    at __awaiter (/home/elizabeth/Programming/Websites/debacle/server/node_modules/@onesignal/node-onesignal/dist/apis/DefaultApi.js:17:12)
    at DefaultApiRequestFactory.createNotification (/home/elizabeth/Programming/Websites/debacle/server/node_modules/@onesignal/node-onesignal/dist/apis/DefaultApi.js:127:16)
    at ObservableDefaultApi.createNotification (/home/elizabeth/Programming/Websites/debacle/server/node_modules/@onesignal/node-onesignal/dist/types/ObservableAPI.js:63:57)
    at PromiseDefaultApi.createNotification (/home/elizabeth/Programming/Websites/debacle/server/node_modules/@onesignal/node-onesignal/dist/types/PromiseAPI.js:18:31)
    at main (/home/elizabeth/Programming/Websites/debacle/server/dist/index.js:166:27)`

**Comment by kesheshyan** [comment]
Hey @SueHeir! Thanks for reporting the issue.

I think you don't need to pass an `Authorization` header when creating a notification:
```typescript
await OneSignalclient.createNotification(notification);
```
Please let us know if there is reason why are you doing this. We might think about improving some interfaces in order to make it simple to use.

Providing `authMethods` when creating a configuration object should be sufficient. 

If the error persist, could you also please include your **user_key_provider** and **app_key_provider** callback functions? IMPORTANT: replace your real tokens with the empty string!

Also we are about to release an updated version of this library that also may negate some problems.
